### ISSUE TITLE
Mutation response isn't an error, but Formol throws a console.error anyway...

### ISSUE THREAD

**Issue by corysimmons** [Kozea/formol#50]
If I do a successful mutation that returns some data in the response, I get this console.error:

https://github.com/Kozea/formol/blob/cf3aad216cfe4fcb4c3aa0351e8caf79706bca20/src/Formol.jsx#L232-L235

I'm using https://github.com/trojanowski/react-apollo-hooks#usemutation Am I doing something wrong?

**Comment by paradoxxxzero** [comment]
On success, your `onSubmit` method should return null/undefined or an empty object. (This warning exists to prevent bad values to be returned by mistake)

**Comment by corysimmons** [comment]
>This warning exists to prevent bad values to be returned by mistake

That shouldn't be the responsibility of Formol though, right?

>You may need an adapter to handle this with useMutation.

Could you provide a really simple example of this? I'm not sure how to do this.

**Comment by paradoxxxzero** [comment]
> > This warning exists to prevent bad values to be returned by mistake
> 
> That shouldn't be the responsibility of Formol though, right?

I think it is, since formol uses the return value of `onSubmit` to set errors and it's easy to forget about it.

> > You may need an adapter to handle this with useMutation.
> 
> Could you provide a really simple example of this? I'm not sure how to do this.

What I meant is that Formol `onSubmit` takes 4 parameters (the new item, the old item, a list of form field names, and a modified flag) and returns through a promise an object with a mapping of errors, which is different from the apollo client `mutate` function that the `useMutation` hook returns.

So you might want to write a custom hook that looks like something like this (this is untested pseudo code):

```js

const useFormolMutation = (itemMutation) => async (item, oldItem) => {
  try {
    // you can also generate diff with oldItem depending on the way you handle mutations
    await itemMutation(item)
  } catch (err) {
    /*  your error logic */
    return {
      errors: {/*field: error*/}
    }
  }
}

const itemMutation = useMutation(ITEM_MUTATION, {
    update: (proxy, mutationResult) => {
      /* your custom update logic */
    },
  });

const onSubmit = useFormolMutation(itemMutation);

return (
  <Formol onSubmit={onSubmit}>
...
```

**Comment by paradoxxxzero** [comment]
Did you manage to plug it?

**Comment by corysimmons** [comment]
No, I stopped using Formol.
